# OneBot机器人设置
bot:
  # OneBot WebSocket地址
  ws-url: "ws://127.0.0.1:3001"
  # 管理员QQ号列表
  admins:
    - 123456789
  # 消息互通群号
  groups:
    - 114890266  # 你的群号
    - 762054349  # 其他需要互通的群号
    - 773981346
  # 重连设置
  reconnect:
    enabled: true
    delay: 30  # 重连延迟（秒）
    max-attempts: 5  # 最大重连次数
    # 重连间隔递增（每次失败后增加延迟）
    increase-delay: true
    # 最大重连延迟（秒）
    max-delay: 300
  # 心跳设置
  heartbeat:
    enabled: true
    interval: 30  # 心跳间隔（秒）
    timeout: 10   # 心跳超时（秒）

# 消息过滤设置
message-filter:
  # 最大消息长度
  max-length: 500
  # 消息速率限制（每分钟）
  rate-limit: 60
  # 敏感词过滤
  word-filter:
    enabled: true
    # 替换为的字符
    replace-with: "*"
    # 敏感词列表
    words: []
  # 命令前缀
  command-prefix: "!"
  # 是否允许空消息
  allow-empty: false
  # 是否允许纯图片消息
  allow-pure-image: true

# 消息格式
message-format:
  # QQ到MC的消息格式
  qq-to-mc: "§b[QQ] §f{sender}: {message}"
  # MC到QQ的消息格式
  mc-to-qq: "[MC] {player}: {message}"
  # 系统消息格式
  system: "§e[系统] §f{message}"
  # 错误消息格式
  error: "§c[错误] §f{message}"
  # 成功消息格式
  success: "§a[成功] §f{message}"

# 白名单设置
whitelist:
  # 是否启用白名单
  enabled: true
  # 绑定模式: "direct" 或 "verify"
  bind-mode: "verify"
  # 验证码设置
  verify:
    # 验证码长度
    length: 6
    # 验证码有效期（分钟）
    expire: 5
    # 验证码格式 (number: 纯数字, mixed: 数字字母混合)
    format: "number"
    # 验证失败次数限制
    max-attempts: 3
    # 验证码冷却时间（秒）
    cooldown: 60
  # 每个QQ号最大绑定数量
  max-bindings-per-qq: 1
  # 绑定冷却时间（分钟）
  bind-cooldown: 60
  # 验证消息格式
  messages:
    verify-sent: "验证码已发送至游戏内，请在游戏中输入：/mcq verify <验证码> 完成绑定"
    verify-expired: "验证码已过期，请重新申请"
    verify-invalid: "验证码错误，请重新输入"
    verify-success: "绑定成功！"
    verify-max-attempts: "验证失败次数过多，请重新申请验证码"
  # 强制绑定设置
  force-bind:
    enabled: true
    allow-join: true
    kick-delay: 300
    kick-message: "请在QQ群中发送 !bind <游戏ID> 完成白名单绑定"
    join-message: "§c[MCQ] §f请在 {time} 秒内完成QQ白名单绑定，否则将被踢出服务器"
    remind-interval: 60
    # 踢出后冷却时间（分钟）
    rejoin-cooldown: 5

# 命令权限设置
permissions:
  # 管理员命令前缀
  admin-prefix: "!admin"
  # 普通命令前缀
  user-prefix: "!"

# 状态显示设置
status:
  # 是否在状态中显示在线玩家列表
  show-player-list: true
  # 是否显示内存使用情况
  show-memory: true
  # 是否显示TPS
  show-tps: true
  # 状态命令冷却时间（秒）
  cooldown: 30

# 命令设置
commands:
  status:
    name: "status"
    aliases: ["服务器", "在线"]
    permission: "mcq.status"
    cooldown: 30
    admin-only: false
    usage: "!status"
    description: "查看服务器状态"
    actions:
      - "status"
  
  bind:
    name: "bind"
    aliases: ["绑定"]
    permission: "mcq.bind"
    cooldown: 60
    admin-only: false
    usage: "!bind <游戏ID>"
    description: "绑定白名单"
    actions:
      - "bind {arg1}"
  
  unbind:
    name: "unbind"
    aliases: ["解绑"]
    permission: "mcq.unbind"
    cooldown: 60
    admin-only: false
    usage: "!unbind <游戏ID>"
    description: "解绑白名单"
    actions:
      - "unbind {arg1}"
  
  reload:
    name: "reload"
    aliases: ["重载"]
    permission: "mcq.admin.reload"
    cooldown: 0
    admin-only: true
    usage: "!admin reload"
    description: "重载配置文件"
    actions:
      - "reload"
  
  tps:
    name: "tps"
    aliases: ["延迟"]
    permission: "mcq.tps"
    cooldown: 10
    admin-only: false
    usage: "!tps"
    description: "查看服务器TPS"
    actions:
      - "tps"
  
  broadcast:
    name: "broadcast"
    aliases: ["公告", "广播"]
    permission: "mcq.admin.broadcast"
    cooldown: 30
    admin-only: true
    usage: "!admin broadcast <消息>"
    description: "发送全服公告"
    actions:
      - "broadcast {args}"
      - "qq_broadcast {args}"

# 日志设置
logging:
  # 日志级别 (ALL, FINEST, FINER, FINE, CONFIG, INFO, WARNING, SEVERE, OFF)
  level: INFO
  # 是否记录详细错误信息
  detailed-errors: true
  # 是否记录调试信息
  debug: false
  # 是否记录WebSocket通信日志
  websocket: true
  # 是否记录命令执行日志
  commands: true
  # 是否记录消息转发日志
  messages: true
  # 是否记录性能监控日志
  performance: false
  # 是否记录API调用日志
  api: false
  # 是否记录白名单操作日志
  whitelist: true
  # 文件日志
  file:
    enabled: true
    # 日志文件路径
    path: "logs/mcq.log"
    # 日志保留天数
    keep-days: 7
    # 单个日志文件大小限制（MB）
    max-size: 10
  # 错误日志过滤
  error-filter:
    # 忽略的错误类型
    ignored-exceptions:
      - "java.net.ConnectException"
      - "java.io.IOException"
      - "java.net.SocketTimeoutException"
    # 错误消息去重时间(秒)
    dedup-time: 60
    # 最大错误历史记录数
    max-history: 1000
    # 定期清理错误历史
    cleanup-interval: 3600

# 性能监控
performance:
  enabled: true
  # 监控间隔（秒）
  interval: 300
  # TPS警告阈值
  tps-warning: 18.0
  # 内存警告阈值（百分比）
  memory-warning: 80
  # 是否发送警告消息到QQ群
  send-warnings: true 